# Generated by Django 3.2.3 on 2021-05-17 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSerie', models.CharField(max_length=150)),
                ('dateAchat', models.DateTimeField(default=datetime.datetime(2021, 5, 17, 18, 52, 43, 40910, tzinfo=utc), verbose_name="date d'ajoute")),
                ('garantie', models.CharField(max_length=100)),
                ('lieuAchat', models.CharField(max_length=100)),
                ('prixAchat', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('dateMaintenance', models.DateTimeField(default=datetime.datetime(2021, 5, 17, 18, 52, 43, 40910, tzinfo=utc), verbose_name='date de derniere maintenance')),
                ('contrat', models.CharField(max_length=10)),
                ('lieuAffectation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'materiel',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=150)),
                ('Lastname', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Pwd', models.CharField(max_length=150)),
            ],
        ),
    ]
