# Generated by Django 3.2.3 on 2021-05-17 21:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='dateAchat',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 21, 53, 59, 506708, tzinfo=utc), verbose_name="date d'ajoute"),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='dateMaintenance',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 21, 53, 59, 506708, tzinfo=utc), verbose_name='date de derniere maintenance'),
        ),
    ]
